return {
  ensure_installed = {
    "gopls",
    "pyright",
    "ruff",
    "mypy",
    "black",
    "typescript-language-server",
    "eslintd",
    "tailwindcss-language-server",
    "clangd",
    "clang-format",
    "json-lsp",
    "css-lsp",
    "stylua",
    "sqlfmt",
    "beautysh",
    "misspell",
    "checkmake",
    "marksman",
    "grammarly-languageserver",
    "prettierd",
  },
}
